#!/usr/bin/env node
/*
 * build-single.js
 *
 * Builds WaterSort.html: a fully self-contained, single-file build of the
 * Water Sort Puzzle game. It inlines style.css and game.js and the favicon
 * (as a data: URI) directly into the HTML so the page makes zero external
 * requests. This lets it be opened directly from a phone's file manager
 * (content:// URIs), file://, or any other context where relative
 * subresource paths would otherwise fail to load.
 *
 * It intentionally strips anything that requires external files:
 * the manifest link, icon links, the service worker registration, and the
 * "Install app" button/handling — none of that can work (or is meaningful)
 * in a single opened HTML file.
 *
 * Run with: node build-single.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

// Escape sequences that would prematurely close a <script> or <style> tag
// when embedded inside HTML.
function safeForScript(js) {
  return js.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
}

function safeForStyle(css) {
  return css.replace(/<\/style/gi, '<\\/style');
}

const indexHtml = read('index.html');
const css = read('style.css');
const js = read('game.js');
const faviconSvg = read('favicon.svg');

const faviconDataUri =
  'data:image/svg+xml;base64,' + Buffer.from(faviconSvg, 'utf8').toString('base64');

let out = indexHtml;

// Replace <head> external resource links with an inlined favicon only.
out = out.replace(
  /<link rel="manifest"[^>]*\/>\s*\n?/,
  ''
);
out = out.replace(
  /<link rel="icon"[^>]*\/>\s*\n?/,
  `<link rel="icon" href="${faviconDataUri}" type="image/svg+xml" />\n`
);
out = out.replace(
  /<link rel="apple-touch-icon"[^>]*\/>\s*\n?/,
  ''
);

// Inline stylesheet.
out = out.replace(
  /<link rel="stylesheet" href="style\.css" \/>/,
  `<style>\n${safeForStyle(css)}\n</style>`
);

// Remove the "Install app" button entirely (it can never work in this build).
out = out.replace(
  /\s*<button id="btn-install"[^>]*>[^<]*<\/button>\s*\n?/,
  '\n'
);

// Replace <script src="game.js"></script> with the inlined game logic.
out = out.replace(
  /<script src="game\.js"><\/script>/,
  `<script>\n${safeForScript(js)}\n</script>`
);

// Replace the trailing inline script (service worker registration + install
// prompt handling) with nothing — none of it applies to a single-file build,
// and it must not attempt any network/subresource request.
out = out.replace(
  /<script>\s*\(function \(\) \{[\s\S]*?window\.addEventListener\('appinstalled'[\s\S]*?\}\)\(\);\s*<\/script>/,
  ''
);

// Add a small marker comment so it's obvious this file is generated.
out = out.replace(
  '<title>מיון בקבוקים</title>',
  '<title>מיון בקבוקים</title>\n<!-- This file is generated by build-single.js from index.html, style.css and game.js. Do not edit directly. -->'
);

fs.writeFileSync(path.join(ROOT, 'WaterSort.html'), out);
console.log('Wrote WaterSort.html (' + fs.statSync(path.join(ROOT, 'WaterSort.html')).size + ' bytes)');
